---
title: "nexus_floordata"
author: "Grace Nunnelley"
date: "2023-02-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(tidyverse)
library(seasonal)
library(naniar)
library(leaflet)
library(maptools)
library(rgeos)
library(tidyverse)
library(rgdal)
library(sf)
library(ncdf4)
library(readr)
```

```{r}
lib_df <- read_csv("Lib_hours.zip")
names(lib_df)[names(lib_df)=="Average Occupancy"] <- "avg_occ"
names(lib_df)[names(lib_df)=="Peak Occupancy"] <- "peak_occ"
lib_df
```
```{r}
lib_df$ts_time<-mdy_hm(lib_df$Timestamp)
# lib_df$ts_time
```

```{r}
# hypothetical plot, needs filtering, generalize areas
# create function for this, input values fro start/freq) 
lib_df$open <- ts(lib_df$avg_occ, start = c(2021,9), freq=365)
plot(lib_df$open)
```

```{r}
all<-lib_df[lib_df$Location == 'UCSB Library',]
all$open <- ts(all$avg_occ, start = c(2021,9), freq=24)
plot(all$open)
```
```{r}
all<-lib_df[lib_df$Location == 'UCSB Library',]
# https://stackoverflow.com/questions/66375745/using-lubridate-function-to-conditionally-change-year-in-date
all$open <- ts(all$avg_occ, start = c(2021,9), freq=24)
plot(all$open)
```

```{r}
first<-lib_df[lib_df$Location == '1st Floor',]
first
first$open <- ts(first$avg_occ, start = c(2021,9), freq=24)
plot(first$open)
```
